<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>TCSystem.Gps</AssemblyName>
        <RootNamespace>TCSystem.Gps</RootNamespace>
        <PackageTags>C#, Gps Utilities</PackageTags>
        <Description>Provides Reader/Writer for reading GPS data from Google takeout</Description>
    </PropertyGroup>

    <Import Project="..\Packaging.props"/>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="10.0.11"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Tests\**"/>
        <EmbeddedResource Remove="Tests\**"/>
        <None Remove="Tests\**"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MetaData\TCSystem.MetaData.csproj"/>
    </ItemGroup>

</Project>