name: Analyze with Sonar
on:
  push:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  build:
    name: Analyze
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Restore Dependencies
        run: dotnet restore

      - name: Restore Tools
        run: dotnet tool restore

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          dotnet sonarscanner begin /k:"TCSystemCS" /o:"tgoessler" /d:sonar.verbose=true /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="**/coverage.net8.0.opencover.xml" /d:sonar.host.url="https://sonarcloud.io" /v:"5.0.0"
          dotnet build -c Debug --no-restore
          dotnet test  -c Debug --no-build --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"