name: Deploy

on:
  workflow_dispatch:
    branches: [ main, develop ]
    inputs:
      IsCiBuild:
        description: 'Is Continues Integration Build'
        required: true
        default: true
        type: boolean
jobs:
  setup_timestamp:
    runs-on: windows-latest
    outputs:
      timestamp: ${{ steps.get_timestamp.outputs.timestamp }}
    steps:
      - id: get_timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M')" >> $Env:GITHUB_OUTPUT

  deploy:
    runs-on: windows-latest
    needs: setup_timestamp

    steps:
    - name: Print timestamp
      run: echo "The timestamp is ${{ needs.setup_timestamp.outputs.timestamp }}"

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: '5.x'

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Tests
      run: dotnet test -c Release --no-restore

    - name: Deploy
      run: dotnet msbuild TCSystem.sln -t:Pack,NugetPush -p:Configuration=Release,DevelopmentVersionSuffix=-ci.${{ needs.setup_timestamp.outputs.timestamp }},IsCiBuild=${{ github.event.inputs.IsCiBuild }}
